//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHunt2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImage
    {
        public byte[] ImgId { get; set; }
        public byte[] ImgName { get; set; }
    }
}
