//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHunt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Cus_Id { get; set; }
        public string Cus_First { get; set; }
        public string Cus_Last { get; set; }
        public string Cus_Gender { get; set; }
        public Nullable<System.DateTime> Cus_DOB { get; set; }
        public string Cus_Street { get; set; }
        public string Cus_City { get; set; }
        public string Cus_Phone { get; set; }
        public string Cus_Email { get; set; }
    }
}
