//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHunt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int Owner_Id { get; set; }
        public string Own_First { get; set; }
        public string Own_Last { get; set; }
        public string Own_Gender { get; set; }
        public Nullable<System.DateTime> Own_DOB { get; set; }
        public string Own_Street { get; set; }
        public string Own_City { get; set; }
        public string Own_Phone { get; set; }
        public string Own_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
    }
}
