//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHunt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int PreId { get; set; }
        public Nullable<int> Bedroom { get; set; }
        public string Location { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Baths { get; set; }
        public string NearbyLocation { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
