//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHunt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.PropertyAgents = new HashSet<PropertyAgent>();
        }
    
        public int Prop_Id { get; set; }
        public string Prop_Street { get; set; }
        public string Prop_City { get; set; }
        public Nullable<int> Prop_NumOfBed { get; set; }
        public Nullable<int> Prop_NumOfBath { get; set; }
        public string Prop_Condition { get; set; }
        public Nullable<decimal> Prop_Price { get; set; }
        public string Prop_Description { get; set; }
        public string Prop_Approved { get; set; }
        public string Id { get; set; }
        public byte[] Prop_Img { get; set; }
        public Nullable<int> Prop_Lat { get; set; }
        public Nullable<int> Prop_Long { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyAgent> PropertyAgents { get; set; }
    }
}
