//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHunt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAgent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyAgent()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int PAId { get; set; }
        public int Prop_Id { get; set; }
        public string Id { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string InspectionStatus { get; set; }
        public string SpecialCode { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
