//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHunt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_Id { get; set; }
        public Nullable<int> Prop_Id { get; set; }
        public string Prop_Street { get; set; }
        public string Prop_City { get; set; }
        public string Id { get; set; }
        public Nullable<decimal> Prop_Price { get; set; }
        public Nullable<decimal> Prop_Bond { get; set; }
        public Nullable<System.DateTime> Prop_Date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Property Property { get; set; }
    }
}
